# Database options
database:
    
    # Whether or not to connect to MySQL. If false, GoldenApple will
    # use SQLite instead.
    useMySQL: false
    
    # The host to connect to when connecting to a MySQL database.
    # (Only applicable if using MySQL)
    host: 'localhost'
    
    # The database to store GoldenApple data into. (Only applicable
    # if using MySQL)
    database: 'ga'
    
    # The username to be given when authenticating for access to the
    # database. (Only applicable if using MySQL)
    user: ''
    
    # The password to be given when authenticating for access to the
    # database. (Only applicable if using MySQL)
    password: ''
    
    # The path (relative to the craftbukkit JAR) at which the SQLite
    # database is located. (Only applicable if using SQLite)
    path: 'plugins/GoldenApple/database.db'
    
# Player message options
message:

    # The default locale that should be used for new players. (Note
    # that each user can change their locale)
    defaultLocale: 'en-US'
    
    # A list of available locales. These should be located within the
    # 'lang' directory of the GoldenApple JAR.
    availableLocales:
        - 'en-US'
    
    # Whether or not to display debugging messages to users. (It is
    # recommended that this setting is kept disabled, as enabling it
    # on a public server may compromise security)
    verbose: false

# Policy settings for ensuring that security is not breached
securityPolicy:
    
    # Determines whether or not the server should be shut down if a
    # module fails to load on server startup. It is recommended to
    # keep this enabled in order to prevent griefing should an anti-
    # griefing module unexpectedly fail to load.
    shutdownOnFailedModuleLoad: true
    
    # Determines whether or not to include extended information in
    # crash dumps. When enabled, additional information, such as SQL
    # row values will be logged for debugging purposes. Unless
    # absolutely necessary, this should be kept enabled in order to
    # be able to diagnose bugs quickly and more efficiently.
    dumpExtendedInfo: true
    
    # Disables the /gaown command. Using /gaown as an op grants full
    # permissions. It should be used ONLY ONCE, by you, if you do
    # not have access to the Minecraft console. False allows the
    # command, True disables it.
    disableOwn: false
    
    # Determines whether or not a module is allowed to be loaded
    # into memory on this server. This should ONLY be used if there
    # are security/stability concerns with loading a specific module.
    # True means that the module should be BLOCKED FROM LOADING.
    blockModules:
        lock: false
        area: false
        warp: false
        chat: false
        antigrief: false 

# Options for GoldenApple modules
modules:
    
    # Permissions system options
    permissions:
        
        # A group that players must be in to be able to connect to
        # the server. (Leave blank to allow all users to join)
        reqGroup: ''
        
        # A list of groups that players will be put in by default
        # either when they first connect or are added to the
        # database manually.
        defaultGroups:
            - 'default'
        
        # A list of groups that players who are ops will be added to
        # when they log in, if they are not already in them.
        opGroups:
            - 'admin'
        
        # A list of groups that GoldenApple developers will be added
        # to when they log in, if they are not already in them.
        devGroups:
            - 'dev'
        
        # Whether users will default to complex command syntax or
        # basic command syntax. True for complex syntax, false for
        # basic syntax. Users can change this themselves using
        # /gacomplex.
        defaultComplexCommands: true
        
        # The number of users (who are not logged in) that should
        # be kept in the user cache. A larger cache will mean less
        # database requests, but will require more RAM.
        userCacheSize: 20
        
        # The number of groups that should be kept in the group
        # cache. WARNING: If this value is too low, permission
        # checks may take a long time.
        groupCacheSize: 20
    
    # Lock system options
    lock:
        
        # Determines whether or not the GoldenApple locking system
        # will be loaded or used by default when the server is
        # started.
        enabled: true
        
        # The size of the GoldenApple lock cache. It is recommended
        # to keep this above at least 20 in order to minimize
        # database loading time. A size of 3 or higher is mandatory
        # in order to prevent locks from being double-loaded into
        # memory.
        cacheSize: 100
        
        # Whether or not to display details about the protection when
        # somebody attempts to use it. (It is recommended that this
        # setting is kept disabled, as enabling it on a public server
        # may compromise security)
        verboseError: false
        
        # The Block IDs of blocks that should be automatically locked
        # when a user has /gaautolock enabled.
        autoLockBlocks: [54]
        
        # Determines whether auto-lock will default to on or off for
        # new users.
        autoLockDefault: true
        
    # Chat system options
    chat:
        
        # Determines whether or not GoldenApple will take over chat
        # functions
        enabled: true
        
        # The chat channel that users should join by default when
        # they first log into the server
        defaultChatChannel: 'default'
        
        # A list of words that should be censored in all chat
        # channels
        censorList:
        
        # A list of words that should be censored in chat channels
        # with strict censoring set to on
        strictCensorList:
        
    # Anti-griefing system options
    antigrief:
    
        # Determines the global status of the entire anti-griefing
        # module. WARNING: Setting this to false disables ALL
        # griefing protection, REGARDLESS OF ANY SETTINGS BELOW!!
        enabled: true
        
        # Setting this to true prevents TNT from being activated
        # using redstone. Due to the nature of redstone, this cannot
        # be configured on a per-user basis.
        noRedstoneTnt: true
        
        # Setting this to true prevents TNT from being activated from
        # being next to fire. Due to the nature of fire, this cannot
        # be configured on a per-user basis.
        noFireTnt: true
        
        # Setting this to true prevents flint and steel from being
        # used to light TNT. IMPORTANT: A user with proper
        # permissions can override this setting.
        noLightTnt: true
        
        # Setting this to true prevents creepers from exploding at
        # all. They will be made COMPLETELY PASSIVE.
        noCreeperExplosion: false
        
        # Setting this to true prevents creeper explosions from
        # damaging any blocks. They will still damage players.
        noCreeperBlockDamage: true