CREATE TABLE IF NOT EXISTS Bans (
	ID INTEGER PRIMARY KEY AUTOINCREMENT,
	Target INTEGER NOT NULL,
	Admin INTEGER NULL,
	Reason VARCHAR(256) NOT NULL,
	StartTime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	Duration BIGINT NULL,
	Voided BOOLEAN NOT NULL,
	CONSTRAINT fk_bans_target
		FOREIGN KEY (Target)
		REFERENCES Users(ID)
		ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT fk_bans_admin
		FOREIGN KEY (Admin)
		REFERENCES Users(ID)
		ON DELETE SET NULL ON UPDATE CASCADE
);
