CREATE TABLE IF NOT EXISTS MailArguments (
	MailID INTEGER NOT NULL,
	Argument INTEGER NOT NULL,
	VALUE TEXT NOT NULL,
	CONSTRAINT fk_mailarguments_mailid
		FOREIGN KEY (MailID)
		REFERENCES Mail(ID)
		ON DELETE CASCADE ON UPDATE CASCADE
);