CREATE TABLE IF NOT EXISTS RequestQueues (
	ID INTEGER PRIMARY KEY AUTOINCREMENT,
	Name VARCHAR(32) NOT NULL UNIQUE,
	SendGroup INTEGER NULL,
	ReceiveGroup INTEGER NULL,
	MaxRequestsPerSender INTEGER NOT NULL,
	AllowNoReceiver BOOLEAN NOT NULL,
	CONSTRAINT fk_requestqueues_sendgroup
		FOREIGN KEY (SendGroup)
		REFERENCES Groups(ID)
		ON DELETE SET NULL ON UPDATE CASCADE,
	CONSTRAINT fk_requestqueues_receivegroup
		FOREIGN KEY (ReceiveGroup)
		REFERENCES Groups(ID)
		ON DELETE SET NULL ON UPDATE CASCADE
);
