CREATE TABLE IF NOT EXISTS Warps (
	Name VARCHAR(32) NOT NULL,
	X DOUBLE NOT NULL,
	Y DOUBLE NOT NULL,
	Z DOUBLE NOT NULL,
	Pitch FLOAT NOT NULL,
	Yaw FLOAT NOT NULL,
	World VARCHAR(32) NOT NULL,
	PRIMARY KEY (Name)
);
