name: GoldenApple
version: 1.0.2
main: com.bendude56.goldenapple.GoldenApplePlugin
website: https://www.github.com/bendude56/GoldenApple
authors: [ben_dude56, Deaboy]
softdepend: [Spout, WorldEdit, WorldGuard]
commands:
    gapermissions:
        usage: Use /<command> -? for help
        description: Edits group and user permissions
        aliases: [p, permissions]
    gaverify:
        usage: /<command>
        description: Confirms the use of a potentially dangerous command
        aliases: [verify]
    gamodule:
        usage: Use /<command> -? for help
        description: Controls GoldenApple modules
        aliases: [m, module]
    gaown:
        usage: /<command>
        description: Grants an op full GoldenApple permissions
        aliases: [own]
    galock:
        usage: Use /<command> -? for help
        description: Modifies/creates locks
        aliases: [l, lock]
    gacomplex:
        usage: /<command>
        description: Enables or disables complex GoldenApple commands
        aliases: [complex]
    gaautolock:
        usage: /<command>
        description: Enables or disables auto-lock
        aliases: [autolock]
    game:
        usage: /<command> <action>
        description: Performs the specified action in chat
        aliases: [me]
    galemonpledge:
        usage: /<command>
        description: No, no... I no can clean...
        aliases: [lemonpledge]
    gachannel:
        usage: Use /<command> -? for help
        description: Modifies, joins, and leaves chat channels.
        aliases: [c, channel]
    gaspawn:
        usage: /<command> [world]
        description: Teleports you to the world spawn.
        aliases: [spawn]
    gatp:
        usage: /<command> <player 1> [player 2]
        description: Teleports you to another player or teleports another player to another player
        aliases: [tp]
    gatphere:
        usage: /<command> <player>
        description: Teleports another player to you
        aliases: [tphere]
    gaback:
        usage: /<command>
        description: Teleports you back to before your last teleport
        aliases: [back]
    gahome:
        usage: Use /<command> -? for help
        description: Controls GoldenApple homes
        aliases: [home]
    gasethome:
        usage: '/<command> [Home #] [{public|private}] [Alias]'
        description: Sets your specified home to your current location
        aliases: [sethome]
    gadelhome:
        usage: '/<command> [Home #]'
        description: Deletes the specified home
        aliases: [delhome]
    gaimport:
        usage: /<command> <Import Type> <Import From>
        description: Imports information from another plugin
        aliases: []
    gaban:
        usage: Use /<command> -? for help
        description: Controls banned players
        aliases: [ban, banish, banhammer]
    gaunban:
        usage: /<command> <Player>
        description: Shortcut for unbanning players
        aliases: [unban, pardon]
    gamute:
        usage: Use /<command> -? for help
        description: Controls muted players
        aliases: [mute, silence]
    gaunmute:
        usage: /<command> <Player>
        description: Shortcut for unmuting players
        aliases: [unmute, unsilence]
    gaglobalmute:
        usage: Use /<command> -? for help
        description: Controls globally muted players
        aliases: [globalmute, gmute, globalsilence, gsilence]
    gaunglobalmute:
        usage: /<command> <Player>
        description: Shortcut for un-global muting players
        aliases: [unglobalmute, ungmute, unglobalsilence, ungsilence]
    gawhois:
        usage: /<command> <Player>
        description: Gets ban/mute information about a player
        aliases: [whois]
    gawarp:
        usage: /<command> <Warp> [Player]
        description: Warps you or another player to a named warp
        aliases: [warp]
    gasetwarp:
        usage: /<command> <Warp>
        description: Sets a named warp
        aliases: [setwarp]
    gadelwarp:
        usage: /<command> <Warp>
        description: Deletes a named warp
        aliases: [delwarp]
    gasell:
        usage: /<command> <item> <price per item> [amount]
        description: Creates a new sell offer
        aliases: [sell]
    gabuy:
        usage: /<command> <item> <price per item> [amount]
        description: Creates a new buy offer
        aliases: [buy]
    gaprice:
        usage: /<command> [item]
        description: Gets the average price of the currently held or specified item
        aliases: [price]
    galang:
        usage: /<command> <locale>
        description: Sets your GoldenApple locale
        aliases: [lang, locale]
    gadebug:
        usage: If you don't know what this does, then DON'T TOUCH IT!
        description: GoldenApple debugging commands