name: GoldenApple
version: 1.0.0
main: com.bendude56.goldenapple.GoldenApple
website: https://www.github.com/bendude56/GoldenApple
authors: [ben_dude56, Deaboy]
softdepend: [Spout, WorldEdit]
commands:
    gapermissions:
        usage: Use /<command> -? for help
        description: Edits group and user permissions
        aliases: [p, permissions]
    gaverify:
        usage: /<command>
        description: Confirms the use of a potentially dangerous command
        aliases: [verify]
    gamodule:
        usage: Use /<command> -? for help
        description: Controls GoldenApple modules
        aliases: [m, module]
    gaown:
        usage: /<command>
        description: Grants an op full GoldenApple permissions
        aliases: [own]
    galock:
        usage: Use /<command> -? for help
        description: Modifies/creates locks
        aliases: [l, lock]
    gacomplex:
        usage: /<command>
        description: Enables or disables complex GoldenApple commands
        aliases: [complex]
    gaautolock:
        usage: /<command>
        description: Enables or disables auto-lock
        aliases: [autolock]
    game:
        usage: /<command> <action>
        description: Performs the specified action in chat
        aliases: [me]
    gachannel:
        usage: Use /<command> -? for help
        description: Modifies, joins, and leaves chat channels.
        aliases: [c, channel]
    gaspawn:
        usage: /<command> [world]
        description: Teleports you to the world spawn.
        aliases: [spawn]
    gatp:
        usage: /<command> <player 1> [player 2]
        description: Teleports you to another player or teleports another player to another player
        aliases: [tp]
    gatphere:
        usage: /<command> <player>
        description: Teleports another player to you
        aliases: [tphere]
    gaback:
        usage: /<command>
        description: Teleports you back to before your last teleport
        aliases: [back]