CREATE TABLE IF NOT EXISTS AreaRegions (
	ID BIGINT PRIMARY KEY AUTO_INCREMENT,
	AreaID BIGINT NOT NULL,
	World VARCHAR(128) NOT NULL,
	MinX DOUBLE NOT NULL,
	MinY DOUBLE NOT NULL,
	MinZ DOUBLE NOT NULL,
	MaxX DOUBLE NOT NULL,
	MaxY DOUBLE NOT NULL,
	MaxZ DOUBLE NOT NULL,
	IgnoreY BOOLEAN NOT NULL,
	Shape INT NOT NULL,
	INDEX ind_arearegions_loc (World ASC, MinX ASC, MinY ASC, MinZ ASC, MaxX ASC, MaxY ASC, MaxZ ASC),
	CONSTRAINT fk_arearegions_areaid
		FOREIGN KEY (AreaID)
		REFERENCES Areas(ID)
		ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB