CREATE TABLE IF NOT EXISTS Channels (
	Identifier CHAR(32) PRIMARY KEY,
	DisplayName VARCHAR(64) NULL,
	MOTD VARCHAR(255) NULL,
	StrictCensor BOOLEAN NOT NULL,
	DefaultLevel INT NOT NULL
) ENGINE=InnoDB