CREATE TABLE IF NOT EXISTS Groups (
	ID BIGINT PRIMARY KEY AUTO_INCREMENT,
	Name VARCHAR(128) NOT NULL UNIQUE,
	Priority INT NOT NULL,
	ChatColor CHAR(1) NULL,
	Prefix VARCHAR(32) NULL
) ENGINE=InnoDB