CREATE TABLE IF NOT EXISTS Homes (
	UserID BIGINT NOT NULL,
	Home INT NOT NULL,
	Alias VARCHAR(32) NULL,
	X DOUBLE NOT NULL,
	Y DOUBLE NOT NULL,
	Z DOUBLE NOT NULL,
	Pitch FLOAT NOT NULL,
	Yaw FLOAT NOT NULL,
	World VARCHAR(32) NOT NULL,
	Public BOOLEAN NOT NULL,
	PRIMARY KEY (UserID, Home),
	UNIQUE INDEX (UserID, Alias),
	CONSTRAINT fk_homes_userid
		FOREIGN KEY (UserID)
		REFERENCES Users(ID)
		ON DELETE CASCADE ON UPDATE CASCADE
) Engine=InnoDB