CREATE TABLE IF NOT EXISTS MailArguments (
	MailID BIGINT NOT NULL,
	Argument INT NOT NULL,
	VALUE TEXT NOT NULL,
	CONSTRAINT fk_mailarguments_mailid
		FOREIGN KEY (MailID)
		REFERENCES Mail(ID)
		ON DELETE CASCADE ON UPDATE CASCADE
) Engine=InnoDB