CREATE TABLE IF NOT EXISTS RequestQueues (
	ID BIGINT PRIMARY KEY AUTO_INCREMENT,
	Name VARCHAR(32) NOT NULL UNIQUE,
	SendGroup BIGINT NULL,
	ReceiveGroup BIGINT NULL,
	MaxRequestsPerSender INT NOT NULL,
	AllowNoReceiver BOOLEAN NOT NULL,
	CONSTRAINT fk_requestqueues_sendgroup
		FOREIGN KEY (SendGroup)
		REFERENCES Groups(ID)
		ON DELETE SET NULL ON UPDATE CASCADE,
	CONSTRAINT fk_requestqueues_receivegroup
		FOREIGN KEY (ReceiveGroup)
		REFERENCES Groups(ID)
		ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB