CREATE TABLE IF NOT EXISTS Warnings (
	ID BIGINT PRIMARY KEY AUTO_INCREMENT,
	Target BIGINT NOT NULL,
	Admin BIGINT NULL,
	Reason VARCHAR(256) NOT NULL,
	Time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT fk_warnings_target
		FOREIGN KEY (Target)
		REFERENCES Users(ID)
		ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT fk_warnings_admin
		FOREIGN KEY (Admin)
		REFERENCES Users(ID)
		ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB